[package]
name = "dir-iterator"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[features]
default = ["wildcard"]
wildcard = ["wc"]

[dependencies]
wc = { package = "wildcard", version = "0.2.0", optional = true }
